# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7575151bf32824b3f57e587f7d10ddfe82d0c570d1ad4af5de985f683b333675bea9541f156bea31775b30776a1848315ef916391ae2f0fe8e45cdfeac2d916b

test:
  secret_key_base: e2f01fbd6d74e9f74d0e04bccbaf1620cf2f4c5c012387109ae68d6bfa7396d46d935eb3c44edef6090a8f4bbc25bd47c424231fdacc9404b9ff0c1f7ebca646

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
